volumes:
  foxreviews_local_postgres_data: {}
  foxreviews_local_postgres_data_backups: {}
  foxreviews_local_redis_data: {}

networks:
  default:
    name: foxreviews_network
    driver: bridge
  foxreviews_shared:
    external: true
    name: foxreviews_shared

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: foxreviews_local_django
    container_name: foxreviews_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8003:8000'
    command: /start
    networks:
      - default
      - foxreviews_shared

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: foxreviews_production_postgres
    container_name: foxreviews_local_postgres
    volumes:
      - foxreviews_local_postgres_data:/var/lib/postgresql/18/docker
      - foxreviews_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: foxreviews_local_mailpit
    ports:
      - "8028:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: foxreviews_local_redis
    volumes:
      - foxreviews_local_redis_data:/data

  celeryworker:
    <<: *django
    image: foxreviews_local_celeryworker
    container_name: foxreviews_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: foxreviews_local_celerybeat
    container_name: foxreviews_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: foxreviews_local_flower
    container_name: foxreviews_local_flower
    ports:
      - '5558:5555'
    command: /start-flower
