volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  
  production_redis_data: {}
  


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: foxreviews_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    networks:
      - default
      - foxreviews_shared
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: foxreviews_production_postgres
    shm_size: "2gb"
    ports:
      - "10.8.0.1:5432:5432"
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: foxreviews_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-http.rule=Host(`api.fox-reviews.com`)"
      - "traefik.http.routers.api-http.entrypoints=web"
      - "traefik.http.routers.api-https.rule=Host(`api.fox-reviews.com`)"
      - "traefik.http.routers.api-https.entrypoints=web-secure"
      - "traefik.http.routers.api-https.tls.certresolver=letsencrypt"

  redis:
    image: docker.io/redis:7.2
    
    volumes:
      - production_redis_data:/data
    

  celeryworker:
    <<: *django
    image: foxreviews_production_celeryworker
    command: /start-celeryworker

  cron:
    <<: *django
    image: foxreviews_production_cron
    command: /start-cron

  celerybeat:
    <<: *django
    image: foxreviews_production_celerybeat
    command: /start-celerybeat
    profiles:
      - celery  # Désactivé par défaut, utiliser cron à la place

  flower:
    <<: *django
    image: foxreviews_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

networks:
  default:
    name: foxreviews_production_django
  foxreviews_shared:
    external: true
